version: "3"
services:
  php:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/usr/src/myapp
      - ./logs:/usr/src/myapp/logs
    depends_on:
      - mysql
  mysql:
        image: mysql:latest
        ports:
          - "3306:3306"
        environment:
          MYSQL_ROOT_PASSWORD: mysqlpw
          MYSQL_DATABASE: parser_data
        volumes:
          - ./mysql:/var/lib/mysql

  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - ./redis/data:/data
  obfs4-bridge:
    image: thetorproject/obfs4-bridge:latest
    environment:
      # Exit with an error message if OR_PORT is unset or empty.
      - OR_PORT=${OR_PORT:?Env var OR_PORT is not set.}
      # Exit with an error message if PT_PORT is unset or empty.
      - PT_PORT=${PT_PORT:?Env var PT_PORT is not set.}
      # Exit with an error message if EMAIL is unset or empty.
      - EMAIL=${EMAIL:?Env var EMAIL is not set.}
      # Nickname with default value: "DockerObfs4Bridge"
      - NICKNAME=${NICKNAME:-DockerObfs4Bridge}
    env_file:
      - .env
    ports:
      - ${OR_PORT}:${OR_PORT}
      - ${PT_PORT}:${PT_PORT}
    restart: unless-stopped
